[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 10
ffi = false
via_ir = true

# EVM
evm_version = "cancun"

# Remappings
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/"
]
